name: Server Actions
on:
  push:
    branches:
      - master
    paths:
      - server/**

jobs:
  server_build:
    name: Server Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Tests
        run: sbt test
        working-directory: server/
